### ISSUE TITLE
Question box not responsive in Firefox

### ISSUE THREAD

**Issue by Gustavo-daCosta** [zaidmukaddam/scira#133]
In Firefox, the Question Box is not responsive, so, when i write more than one line of text, instead of expanding the box, my text just goes to next line and the text box create an scroll bar.

![teste](https://github.com/user-attachments/assets/e6dcb837-a8e8-4380-a11f-6994486f1f6a)

System and Browser specs:

Firefox 137.0.1
Windows 10 22H2 19045.5608
Edition	Windows 10 Pro
Version	2009
Build SO	19045.5608

**Comment by UdaySriHarsha** [comment]
> In Firefox, the Question Box is not responsive, so, when i write more than one line of text, instead of expanding the box, my text just goes to next line and the text box create an scroll bar.
> 
> ![teste](https://github.com/user-attachments/assets/e6dcb837-a8e8-4380-a11f-6994486f1f6a) [ ![teste](https://github.com/user-attachments/assets/e6dcb837-a8e8-4380-a11f-6994486f1f6a) ](https://private-user-images.githubusercontent.com/80484719/435418502-e6dcb837-a8e8-4380-a11f-6994486f1f6a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDYzNDA0MTYsIm5iZiI6MTc0NjM0MDExNiwicGF0aCI6Ii84MDQ4NDcxOS80MzU0MTg1MDItZTZkY2I4MzctYThlOC00MzgwLWExMWYtNjk5NDQ4NmYxZjZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTA0VDA2MjgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMTlkMTM4N2FiMDViODY3MzFhYmU3MDk1ZTUzNDYwZjEwMWZhNDA4NzBhM2M0Y2VjMzZmMDk4NTZhMTM1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XdsIzX4v_6Qid7QdPQzIlICbWkokF7yFxH3lG_AKNlE) [ ](https://private-user-images.githubusercontent.com/80484719/435418502-e6dcb837-a8e8-4380-a11f-6994486f1f6a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDYzNDA0MTYsIm5iZiI6MTc0NjM0MDExNiwicGF0aCI6Ii84MDQ4NDcxOS80MzU0MTg1MDItZTZkY2I4MzctYThlOC00MzgwLWExMWYtNjk5NDQ4NmYxZjZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTA0VDA2MjgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMTlkMTM4N2FiMDViODY3MzFhYmU3MDk1ZTUzNDYwZjEwMWZhNDA4NzBhM2M0Y2VjMzZmMDk4NTZhMTM1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XdsIzX4v_6Qid7QdPQzIlICbWkokF7yFxH3lG_AKNlE)
> 
> System and Browser specs:
> 
> Firefox 137.0.1 Windows 10 22H2 19045.5608 Edition Windows 10 Pro Version 2009 Build SO 19045.5608

still happens, i found with scira itself that the 
`Your <textarea> does not auto-resize as you type because it uses resize-none (which disables manual resizing) and lacks any auto-resize logic or attributes.`

**Comment by UdaySriHarsha** [comment]
I've managed to come up with a userstyle(stylus) script to fix this

```css
/* ==UserStyle==
@name           Scira.ai Textarea Fix
@namespace      userstyles.world
@version        1.0.0
@description    Remove textarea height limits on scira.ai
==/UserStyle== */

@-moz-document domain("scira.ai") {
    textarea, [data-slot="textarea"] {
        max-height: none !important;
        min-height: 2em !important;
        height: auto !important;
        resize: none !important;
        overflow-y: auto !important;
    }

    .what-size,
    .flex,
    .field-sizing-content,
    .w-full,
    .rounded-lg,
    .overflow-hidden,
    .overflow-auto,
    .overflow-scroll,
    [data-slot="textarea"] {
        overflow: visible !important;
        max-height: none !important;
        height: auto !important;
    }
}
```
