### ISSUE TITLE
Would be nice if mouse cursor defaulted to pointer

### ISSUE THREAD

**Issue by bernaferrari** [zaidmukaddam/scira#146]
I highly recommend adding

```css
@layer base {
  button:not([disabled]),
  [role="button"]:not([disabled]) {
    cursor: pointer;
  }
}
```
(source https://github.com/shadcn-ui/ui/issues/6843#issuecomment-2698105214)

because I think the experience is way better with pointer mouse cursor.
